FROM almalinux

RUN dnf install -y emacs-nox nc jq \
    && dnf clean all

ENV STAT_DATA_DIR=/var/pc_stats
ENV TZ=Europe/Paris

ENV VINDECODER_EU_APIPREFIX="_no_default_value_"
ENV VINDECODER_EU_SECRET="_no_default_value_"

COPY bin/generateAndSendGELFMessages.sh /usr/local/bin

# defaults to NextCloud user/group
USER 33:33

#ENTRYPOINT [ "/usr/local/bin/generateHrStatsForPeriod.sh" ]
