FROM almalinux

ENV STAT_DATA_DIR=/var/pc_stats
ENV TZ=Europe/Paris

ENV VINDECODER_EU_APIPREFIX
ENV VINDECODER_EU_SECRET

RUN dnf install -y emacs-nox nc jq \
    && dnf clean all

COPY bin/generateAndSendGELFMessages.sh /usr/local/bin

# defaults to NextCloud user/group
USER 33:33

#ENTRYPOINT [ "/usr/local/bin/generateHrStatsForPeriod.sh" ]
